### ISSUE TITLE
create a webpage for cp4waiops-gitops

### ISSUE THREAD

**Issue by gyliu513** [IBM/cp4waiops-gitops#107]
Create a page like this https://cloud-pak-gitops.github.io/website/docs/#/

@morningspace

**Comment by morningspace** [comment]
Tried w/ mkdocs and it looks good, but there's an issue that it will overwrite the `index.yaml` file used to host the helm repo on `gh-pages` branch. More details on this issue: https://github.com/mkdocs/mkdocs/issues/2796.

**Comment by gyliu513** [comment]
PR at https://github.com/IBM/cp4waiops-gitops/pull/109

**Comment by gyliu513** [comment]
PR at https://github.com/IBM/cp4waiops-gitops/pull/109
