### ISSUE TITLE
CP4WAIOps Event Manager deployement through ArgoCD got stuck on couple of pods

### ISSUE THREAD

**Issue by ks-ibm** [IBM/cp4waiops-gitops#127]
Hi all!

After issue #125 my ArgoCD continued. Lots of pods got deployed, but some of them have broken hearts:
![image](https://user-images.githubusercontent.com/102600916/161041785-cee5bed3-d889-421f-819e-e22d81874dab.png)

When looking in my OCP cluster, I see for example these: 
![image](https://user-images.githubusercontent.com/102600916/161041428-55ea7a40-3a60-44f1-be76-c0445d8e74e3.png)

Some of the pods do have errors, for example evtmanager-ibm-hdm-common-ui-uiserver-58fd6bffbd-bclzh:

> > Using TLS certificate located at /internal-tls-keys/tls.crt
> 
> 
>       Using TLS key located at /internal-tls-keys/tls.key
> 
> {"name":"logging","hostname":"evtmanager-ibm-hdm-common-ui-uiserver-58fd6bffbd-bclzh","pid":1,"level":30,"msg":"Logging started","time":"2022-03-31T09:20:09.003Z","v":0}
> {"name":"common-express-server","hostname":"evtmanager-ibm-hdm-common-ui-uiserver-58fd6bffbd-bclzh","pid":1,"level":30,"msg":"\n== Loaded server application ==\n  Package name:     @hdm/akora-app-noi\n  Package version:  12.0.501\n  Base URL:         https://netcool-evtmanager.cp4waiops-em-6c9cbda044ecd11a71bd72721098e1cf-0000.eu-de.containers.appdomain.cloud/\n  HTTP port:        8080\n  HTTPS port:       8443\n  Development Mode: false\n  Require HTTPS:    true\n===============================\n  ","time":"2022-03-31T09:20:09.005Z","v":0}
> {"name":"akora-server.middleware.Session","hostname":"evtmanager-ibm-hdm-common-ui-uiserver-58fd6bffbd-bclzh","pid":1,"level":30,"cookie":{"name":"akora.sid","path":"/","maxage":7200,"samesite":"lax"},"provider":"redis","msg":"Sessions are enabled","time":"2022-03-31T09:20:09.017Z","v":0}
> {"name":"akora-server.routes.ApiProxyRoute","hostname":"evtmanager-ibm-hdm-common-ui-uiserver-58fd6bffbd-bclzh","pid":1,"level":30,"id":"hdm_ea_uiapi","msg":"Creating scoped proxy","time":"2022-03-31T09:20:09.140Z","v":0}
> {"name":"akora-server.routes.ApiProxyRoute","hostname":"evtmanager-ibm-hdm-common-ui-uiserver-58fd6bffbd-bclzh","pid":1,"level":30,"msg":"[HPM] Proxy created: /  -> http://evtmanager-ibm-ea-ui-api-graphql.noi.svc:8080/graphql","time":"2022-03-31T09:20:09.141Z","v":0}
> {"name":"akora-server.routes.ApiProxyRoute","hostname":"evtmanager-ibm-hdm-common-ui-uiserver-58fd6bffbd-bclzh","pid":1,"level":30,"msg":"[HPM] Proxy rewrite rule created: \"^/api/p/hdm_ea_uiapi\" ~> \"\"","time":"2022-03-31T09:20:09.141Z","v":0}
> {"name":"akora-server.routes.ApiProxyRoute","hostname":"evtmanager-ibm-hdm-common-ui-uiserver-58fd6bffbd-bclzh","pid":1,"level":30,"id":"hdm_noi_webgui","msg":"Creating scoped proxy","time":"2022-03-31T09:20:09.141Z","v":0}
> {"name":"akora-server.routes.ApiProxyRoute","hostname":"evtmanager-ibm-hdm-common-ui-uiserver-58fd6bffbd-bclzh","pid":1,"level":30,"msg":"[HPM] Proxy created: /  -> https://evtmanager-webgui.noi.svc:16311/ibm/console/webtop","time":"2022-03-31T09:20:09.142Z","v":0}
> {"name":"akora-server.routes.ApiProxyRoute","hostname":"evtmanager-ibm-hdm-common-ui-uiserver-58fd6bffbd-bclzh","pid":1,"level":30,"msg":"[HPM] Proxy rewrite rule created: \"^/api/p/hdm_noi_webgui\" ~> \"\"","time":"2022-03-31T09:20:09.142Z","v":0}
> {"name":"akora-server.routes.ApiProxyRoute","hostname":"evtmanager-ibm-hdm-common-ui-uiserver-58fd6bffbd-bclzh","pid":1,"level":30,"id":"hdm_cemusers","msg":"Creating scoped proxy","time":"2022-03-31T09:20:09.142Z","v":0}
> {"name":"akora-server.routes.ApiProxyRoute","hostname":"evtmanager-ibm-hdm-common-ui-uiserver-58fd6bffbd-bclzh","pid":1,"level":30,"msg":"[HPM] Proxy created: /  -> http://evtmanager-ibm-cem-cem-users.noi.svc:6002/","time":"2022-03-31T09:20:09.142Z","v":0}
> {"name":"akora-server.routes.ApiProxyRoute","hostname":"evtmanager-ibm-hdm-common-ui-uiserver-58fd6bffbd-bclzh","pid":1,"level":30,"msg":"[HPM] Proxy rewrite rule created: \"^/api/p/hdm_cemusers\" ~> \"\"","time":"2022-03-31T09:20:09.142Z","v":0}
> {"name":"akora-server.routes.ApiProxyRoute","hostname":"evtmanager-ibm-hdm-common-ui-uiserver-58fd6bffbd-bclzh","pid":1,"level":30,"id":"hdm_cem_uiapi","msg":"Creating scoped proxy","time":"2022-03-31T09:20:09.142Z","v":0}
> {"name":"akora-server.routes.ApiProxyRoute","hostname":"evtmanager-ibm-hdm-common-ui-uiserver-58fd6bffbd-bclzh","pid":1,"level":30,"msg":"[HPM] Proxy created: /  -> http://evtmanager-ibm-cem-event-analytics-ui.noi.svc:3201/","time":"2022-03-31T09:20:09.142Z","v":0}
> {"name":"akora-server.routes.ApiProxyRoute","hostname":"evtmanager-ibm-hdm-common-ui-uiserver-58fd6bffbd-bclzh","pid":1,"level":30,"id":"hdm_rba_uiapi","msg":"Creating scoped proxy","time":"2022-03-31T09:20:09.142Z","v":0}
> {"name":"akora-server.routes.ApiProxyRoute","hostname":"evtmanager-ibm-hdm-common-ui-uiserver-58fd6bffbd-bclzh","pid":1,"level":30,"msg":"[HPM] Proxy created: /  -> http://evtmanager-ibm-cem-rba-rbs.noi.svc:3005/","time":"2022-03-31T09:20:09.142Z","v":0}
> {"name":"akora-server.routes.ApiProxyRoute","hostname":"evtmanager-ibm-hdm-common-ui-uiserver-58fd6bffbd-bclzh","pid":1,"level":30,"msg":"[HPM] Proxy rewrite rule created: \"^/api/p/hdm_rba_uiapi\" ~> \"\"","time":"2022-03-31T09:20:09.142Z","v":0}
> {"name":"akora-server.routes.ApiProxyRoute","hostname":"evtmanager-ibm-hdm-common-ui-uiserver-58fd6bffbd-bclzh","pid":1,"level":30,"id":"hdm_rba_legacyui","msg":"Creating scoped proxy","time":"2022-03-31T09:20:09.143Z","v":0}
> {"name":"akora-server.routes.ApiProxyRoute","hostname":"evtmanager-ibm-hdm-common-ui-uiserver-58fd6bffbd-bclzh","pid":1,"level":30,"msg":"[HPM] Proxy created: /  -> http://evtmanager-ibm-cem-rba-rbs.noi.svc:3005/","time":"2022-03-31T09:20:09.143Z","v":0}
> {"name":"akora-server.routes.ApiProxyRoute","hostname":"evtmanager-ibm-hdm-common-ui-uiserver-58fd6bffbd-bclzh","pid":1,"level":30,"id":"hdm_asm_ui_api","msg":"Creating scoped proxy","time":"2022-03-31T09:20:09.143Z","v":0}
> {"name":"akora-server.routes.ApiProxyRoute","hostname":"evtmanager-ibm-hdm-common-ui-uiserver-58fd6bffbd-bclzh","pid":1,"level":30,"msg":"[HPM] Proxy created: /  -> https://evtmanager-topology-ui-api.noi.svc:3080/","time":"2022-03-31T09:20:09.143Z","v":0}
> {"name":"akora-server.routes.ApiProxyRoute","hostname":"evtmanager-ibm-hdm-common-ui-uiserver-58fd6bffbd-bclzh","pid":1,"level":30,"msg":"[HPM] Proxy rewrite rule created: \"^/api/p/hdm_asm_ui_api\" ~> \"\"","time":"2022-03-31T09:20:09.143Z","v":0}
> {"name":"akora-server.routes.ApiProxyRoute","hostname":"evtmanager-ibm-hdm-common-ui-uiserver-58fd6bffbd-bclzh","pid":1,"level":30,"id":"hdm_noi_dashboarding","msg":"Creating scoped proxy","time":"2022-03-31T09:20:09.143Z","v":0}
> {"name":"akora-server.routes.ApiProxyRoute","hostname":"evtmanager-ibm-hdm-common-ui-uiserver-58fd6bffbd-bclzh","pid":1,"level":30,"msg":"[HPM] Proxy created: /  -> http://evtmanager-grafana.noi.svc:3000/","time":"2022-03-31T09:20:09.143Z","v":0}
> {"name":"akora-server.routes.ApiProxyRoute","hostname":"evtmanager-ibm-hdm-common-ui-uiserver-58fd6bffbd-bclzh","pid":1,"level":30,"msg":"[HPM] Proxy rewrite rule created: \"^/api/p/hdm_noi_dashboarding\" ~> \"\"","time":"2022-03-31T09:20:09.143Z","v":0}
> {"name":"akora-server.routes.DashFederationRoute","hostname":"evtmanager-ibm-hdm-common-ui-uiserver-58fd6bffbd-bclzh","pid":1,"level":30,"pages":[{"federateType":["page","widget"],"federated":true,"globalized":[{"language":"ar","label":"Alerts"},{"language":"cs","label":"Výstrahy"},{"language":"de","label":"Alerts"},{"language":"en","label":"Alerts"},{"language":"es","label":"Alertas"},{"language":"fr","label":"Alertes"},{"language":"he","label":"Alerts"},{"language":"hu","label":"Riasztások"},{"language":"it","label":"Avvisi"},{"language":"ja","label":"アラート"},{"language":"ko","label":"경보"},{"language":"pl","label":"Alerty"},{"language":"pt-BR","label":"Alertas"},{"language":"ru","label":"Уведомления"},{"language":"th","label":"Alerts"},{"language":"zh-CN","label":"警报"},{"language":"zh-TW","label":"警示"}],"id":"com.ibm.hdm.noi.alerts.alert-viewer","platforms":["DESKTOP"],"roles":["noi_operator","noi_engineer","noi_lead"],"pageurl":"/aiops/cfd95b7e-3bc7-4006-a4a8-a73a79c71255/federated/alerts","type":"visibl...
> {"name":"akora-server.middleware.Authentication","hostname":"evtmanager-ibm-hdm-common-ui-uiserver-58fd6bffbd-bclzh","pid":1,"level":30,"mode":"openid-cem","msg":"Authentication is enabled","time":"2022-03-31T09:20:09.419Z","v":0}
> {"name":"akora-server.dash-federation.ci","hostname":"evtmanager-ibm-hdm-common-ui-uiserver-58fd6bffbd-bclzh","pid":1,"level":30,"msg":"Check console integration { ci: 'com.ibm.hdm.hdmintegration.ui.ci.cloudanalytics' }","time":"2022-03-31T09:20:09.422Z","v":0}
> TypeError: client_id is required
>     at new BaseClient (/server/node_modules/openid-client/lib/client.js:176:13)
>     at new Client (/server/node_modules/openid-client/lib/client.js:1821:7)
>     at module.exports (/server/lib/middleware/Authentication/modes/openid-cem.js:50:18)
>     at Authentication (/server/lib/middleware/Authentication/index.js:52:14)
>     at module.exports (/server/lib/routes/getHttpRoutes.js:72:53)
>     at routes (/server/lib/routes/index.js:21:22)
>     at Config.applyAppRoutes (/server/lib/index.js:19:32)
>     at App (/server/node_modules/@hdm/common-express-server/lib/App.js:33:10)
>     at AsyncFunction.module.exports.createServers (/server/node_modules/@hdm/common-express-server/lib/index.js:43:15)
>     at module.exports (/server/node_modules/@hdm/common-express-server/lib/index.js:17:40)

As per Slack DM with @morningspace:

> Did quick look, so:
> 
> - CatalogSource refers to [icr.io/cpopen/ibm-operator-catalog:latest](http://icr.io/cpopen/ibm-operator-catalog:latest), that is supposed to be the GA build
> 
> - Subscription uses channel: v1.7, it looks the 3.2.0 docs on IBM Docs haven’t been updated to reflect the latest release for Event Manager, but I’m assuming this is the right channel
> 
> - For those pods w/ broken hearts, I see two of them are caused by ImagePullBackOff, which seems to be the root cause, i.e.: cannot pull images from [cp.icr.io](http://cp.icr.io/). The other two pods are impacted because of this.

Hopefully someone can see a missing link in this?

Thanks!
K.

**Comment by morningspace** [comment]
PR https://github.com/IBM/cp4waiops-gitops/pull/129 is to fix this issue.

**Comment by morningspace** [comment]
I'm going to close this issue since #129 has been merged. @ks-ibm
