### ISSUE TITLE
Update AI Manager helm chart version to fix the GitHub Action failure

### ISSUE THREAD

**Issue by morningspace** [IBM/cp4waiops-gitops#136]
We have recently modified helm chart for AI Manager and Event Manager in PR #132, but did not update the helm chart version. (Event Manager chart version is updated which is good). This breaks the GitHub Action to generate the helm chart packages. More details, please check: https://github.com/IBM/cp4waiops-gitops/runs/5797052801.

We should bump the helm chart version, in this case, AI Manager from 0.0.1 to 0.0.2, anytime when we modify the corresponding helm chart.

**Comment by huang-cn** [comment]
fixed in PR: https://github.com/IBM/cp4waiops-gitops/pull/194
I'm closing this issue
