### ISSUE TITLE
webpage toc layout is not right

### ISSUE THREAD

**Issue by gyliu513** [IBM/cp4waiops-gitops#138]
@morningspace can you check what is wrong with webpage here?

- layout is not right
- content was not updated based on latest changes
- 
<img width="514" alt="image" src="https://user-images.githubusercontent.com/4461983/161864277-f7750817-4683-42ba-a170-891022c90f5e.png">

**Comment by morningspace** [comment]
The reason for "content was not updated based on latest changes" is because of https://github.com/IBM/cp4waiops-gitops/issues/137.

**Comment by morningspace** [comment]
For "layout is not right", this seems to be an issue of [mkdocs](https://www.mkdocs.org/). Will check w/ dev owner.

**Comment by morningspace** [comment]
Issue resolved after read https://github.com/mkdocs/mkdocs/issues/545#issuecomment-522196661.
