### ISSUE TITLE
Missing SCC for Event Manager service account?

### ISSUE THREAD

**Issue by nastacio** [IBM/cp4waiops-gitops#139]
The Event Manager installation instructions (https://www.ibm.com/docs/en/noi/1.6.4?topic=openshift-preparing) state that the admin must associate an SCC with the `noi-service-account`, but I do not see that in the repo, only the service account itself:
https://github.com/IBM/cp4waiops-gitops/blob/main/config/3.3/event-manager/templates/noi-serviceaccount.yaml

Also note that the SA cannot be in the repo, because OCP attaches additional secrets to service accounts and then Argo and OCP start to overwrite each other's changes periodically: Argo shows the resource as out-of-sync because it has an extra secret and deletes it, then OCP adds the secret again.

Unfortunately, the only way to avoid this problem is to use a procedural approach to detect, create, and patch the service account, as needed:

https://github.com/IBM/cloudpak-gitops/blob/018986020947e8e2d09f10b390b570fb1a6b35d8/config/cloudpaks/cp4aiops/install-emgr/templates/subscriptions/030-sync-prereqs.yaml#L54

**Comment by nastacio** [comment]
For `1`, I think it is always best to follow the product documentation as closely as possible. It is hard to tell why they chose to write them in that (very different) manner and one possibility is that they tried the rolebinding and certain things did not work in the way (or order) they expected.

For `2`, relying on `ignoreDifferences` is somewhat risky because the product has specific expectations on the contents of that field.

**Comment by huang-cn** [comment]
@nastacio I'm updating to remove the SA in repo and use the sync hook instead.

**Comment by morningspace** [comment]
Closing as work has been done.
