### ISSUE TITLE
Refactor repo folder layout to align with IBM/cloudpak-gitops

### ISSUE THREAD

**Issue by gyliu513** [IBM/cp4waiops-gitops#151]
```
cp4waiops
   |
   | -- foundation
   |           |
   |           | -- ibm-operator-catalogsource
   |
   | -- aimanager
   |          |
   |          | -- operator
   |          | -- operands
   |
   | -- eventmanager
              |
              | -- operator
              | -- operands
```

**Comment by morningspace** [comment]
To fully align w/ the folder tree in https://github.com/IBM/cloudpak-gitops as much as possible, I'm proposing the below tree for CP4WAIOps:

- Drop `config/cloudpaks` and uplift all sub-folders since we only work on CP4WAIOps. No other cloud pak in this repo.
- Rename `config/cloudpaks/cp4aiops` to be `config/cp4waiops` as `CP4WAIOps` is the official name for the product.
- Move `3.1`, `3.2`, `3.3` to their own branches per [this blog](https://dnastacio.medium.com/gitops-repositories-the-right-way-part-1-mapping-strategies-6409dff758b5) by @nastacio and `release-3.4` identical to `main` for now.

```console
.
└── config
    ├── cp-shared
    └── cp4waiops
        ├── install-aimgr
        │   └── templates
        │       ├── resources
        │       └── subscriptions
        ├── install-emgr
        │   └── templates
        │       ├── resources
        │       └── subscriptions
        └── tech-preview (all gitops installation configuration as tech preview features)
            ├── all-in-one (the all-in-one configuration using app-of-apps pattern to support both in-cluster and remote install)
            ├── argocd (argocd customization configuration)
            │   ├── kubernetes (customization for argocd run in kubernetes)
            │   └── openshift (customization for argocd run in openshift)
            ├── ceph (sample storage install using ceph)
            ├── clusters (sample cluster provisioning install)
            │   └── fyre
            └── custom-sizing (aiops custom sizing sample configuration)
                ├── values.x-small.yaml
                ├── values.x-small.idle-workload.yaml
                ├── values.x-small.lad.yaml
                ├── values.x-small.mad.yaml
                └── values.yaml
```

@gyliu513 @huang-cn

**Comment by gyliu513** [comment]
@morningspace +1 for the layout, this looks good, thanks!

**Comment by nastacio** [comment]
> * Drop `config/cloudpaks` and uplift all sub-folders since we only work on CP4WAIOps. No other cloud pak in this repo.
> Rename config/cloudpaks/cp4aiops to be config/cp4waiops as CP4WAIOps is the official name for the product.

Agree. A few comments:

1. I would still keep "argocd" and "ceph" directly under "config" though.
1. What you are calling "tech-preview/all-in-one" is under "config/argocd-cloudpaks/cp4aiops" right now. Would it make more sense for "tech-preview/all-in-one to be "config/argocd-cp4waiops" ?
1. The name "tech-preview". As I understand, the whole repo is a tech-preview in 3.3.1. The presence of that folder suggests some things (the things outside that folder) are not a tech-preview, which may be misleading.
1. I would move all the Fyre discussion to a private IBM repo.

> Move 3.1, 3.2, 3.3 to their own branches per [this blog](https://dnastacio.medium.com/gitops-repositories-the-right-way-part-1-mapping-strategies-6409dff758b5) by @nastacio and release-3.4 identical to main for now.

I don't know the details about the release management for the product and this repo, but if they are fully aligned, I like it too.

Please, feel free to reach out via DM for more interactive discussion or review.

**Comment by gyliu513** [comment]
@nastacio I was going to book a meeting with you probably next week to discuss this, thanks!

**Comment by morningspace** [comment]
Thanks @nastacio so much for your feedback, I've updated the tree per your comments as below. For "tech-preview", just to clarify, according to the plan, we are targeting some of these in this repo remained as tech preview since 3.3, while others will be advanced in the next release.

```console
.
└── config
    ├── argocd                    (argocd custom configuration)
    │   ├── kubernetes            (argocd custom configuration runs in kubernetes)
    │   └── openshift             (argocd custom configuration runs in openshift)
    ├── ceph                      (sample storage install using ceph)
    ├── cp-shared                 (cloud pak shared gitops configuration)
    └── cp4waiops                 (cp4waiops gitops configuration)
        ├── install-aimgr         (aimanager gitops configuration)
        │   └── templates
        │       ├── resources     (operand gitops configuration)
        │       └── subscriptions (operator gitops configuration)
        ├── install-emgr          (eventmanager gitops configuration)
        │   └── templates
        │       ├── resources     (operand gitops configuration)
        │       └── subscriptions (operator gitops configuration)
        └── tech-preview          (all gitops install configuration as tech preview features)
            ├── argocd-cp4waiops  (all-in-one configuration using app-of-apps pattern supports both in-cluster and remote install)
            └── custom-sizing     (aiops custom sizing sample configuration)
                ├── values.x-small.yaml
                ├── values.x-small.idle-workload.yaml
                ├── values.x-small.lad.yaml
                ├── values.x-small.mad.yaml
                └── values.yaml
```

**Comment by morningspace** [comment]
After further discussion, we've determined to remove the `tech-preview` folder to avoid any possible confusion. Those that are subject to change or unsupported will be well documented in corresponding docs. So, below is the final version. Thanks to @nastacio @gyliu513 !

```console
.
└── config
    ├── argocd-all-in-one         (all-in-one configuration using app-of-apps pattern supports both in-cluster and remote install)
    ├── argocd                    (argocd custom configuration)
    │   ├── kubernetes            (argocd custom configuration runs in kubernetes)
    │   └── openshift             (argocd custom configuration runs in openshift)
    ├── ceph                      (sample storage install using ceph)
    ├── cp-shared                 (cloud pak shared gitops configuration)
    └── cp4waiops                 (cp4waiops gitops configuration)
        ├── install-aimgr         (aimanager gitops configuration)
        │   └── templates
        │       ├── resources     (operand gitops configuration)
        │       └── subscriptions (operator gitops configuration)
        ├── install-emgr          (eventmanager gitops configuration)
        │   └── templates
        │       ├── resources     (operand gitops configuration)
        │       └── subscriptions (operator gitops configuration)
        └── custom-sizing         (aiops custom sizing sample configuration)
            ├── values.x-small.yaml
            ├── values.x-small.idle-workload.yaml
            ├── values.x-small.lad.yaml
            ├── values.x-small.mad.yaml
            └── values.yaml
```

**Comment by morningspace** [comment]
Closing it since work has been done.
