### ISSUE TITLE
Correct the default value of cp4waiops.version param in all-in-one template

### ISSUE THREAD

**Issue by morningspace** [IBM/cp4waiops-gitops#210]
The all-in-one template using v3.3 as the default value for cp4waiops.version param even it's on 3.4 branch. See below UI:

<img width="1254" alt="image" src="https://user-images.githubusercontent.com/16119920/187377391-6413e3db-b048-44e8-9f84-be0f9b4a0264.png">

Also, the [_helpers.tpl](https://github.com/IBM/cp4waiops-gitops/blob/release-3.4/config/all-in-one/templates/_helpers.tpl) in all-in-one template needs to be corrected since we do not mix multiple per-release templates on the same branch now. e.g.: there is no `config/3.2/ai-manager` any more.

```yaml
{{- define "cp4waiops.aimanager.configPath" -}}
  {{- if eq .Values.cp4waiops.version "v3.2" }}
  {{- printf "config/3.2/ai-manager" -}}
  {{- else if eq .Values.cp4waiops.version "v3.3" }}
  {{- printf "config/cp4waiops/install-aimgr" -}}
  {{- else if eq .Values.cp4waiops.version "v3.4" }}
  {{- printf "config/cp4waiops/install-aimgr" -}}
  {{- else }}
  {{- fail "The CP4WAIOps all in one chart only supports release v3.2, v3.3, v3.4." }}
  {{- end }}
{{- end -}}
```

**Comment by huang-cn** [comment]
@morningspace all-in-one version and mixed version fixed in this PR https://github.com/IBM/cp4waiops-gitops/pull/214.
Closing this issue.
