### ISSUE TITLE
Suggest to use the new helm-based install method for ceph storage

### ISSUE THREAD

**Issue by morningspace** [IBM/cp4waiops-gitops#32]
A couple of issues for the current ceph YAML manifests stored in this repo:
- It uses an old ceph version.
- It's very often that you will see OutOfSync when using it to deploy ceph especially when you use manual sync. In such case, you will have to re-sync to get rid of OutOfSync. This is because some fields defined in ceph YAML manifests stored in repo will have different appearance but w/ the same meaning at runtime, e.g.: some field will be missing at runtime, while in YAML manifest, it has "enabled" field w/ false value. They are the same thing but will be treated as difference by Argo CD. That's why you see OutOfSync.
- It does not handle the healthiness properly, where it saids healthy but some ceph pods are still being launched.

All these issues are resolved in https://github.com/cloud-pak-gitops/sample-app-gitops, where it uses robot-shop as a sample app and use ceph as storage too.

With that, suggest to follow sample-app-gitops repo to update this repo. Also, suggest to create a separate repo to host all helm charts centrally, including the ceph one, rather than put them under each gitops repo like sample-app-gitops.

**Comment by gyliu513** [comment]
@morningspace can we close this one?

**Comment by morningspace** [comment]
yes, I see bullet 2 & 3 are addressed, although we are still using an old ceph, this won't be a blocker for now.
