### ISSUE TITLE
Upload a video to share how to install cloud pak with gitops

### ISSUE THREAD

**Issue by gyliu513** [IBM/cp4waiops-gitops#34]
@cloud-pak-gitops/cp4wiops-gitops-core

**Comment by gyliu513** [comment]
two videos:
- on-line install
- airgap install

**Comment by liyanwei93** [comment]
On-line install video: https://youtu.be/xpinVzXcJBs

**Comment by liyanwei93** [comment]
Airgap install video: https://youtu.be/3cpmjMXgpRI

**Comment by morningspace** [comment]
Closing it since work has been done.
