### ISSUE TITLE
Refactor folder structure for 3.2/3.3 release to keep consistency

### ISSUE THREAD

**Issue by morningspace** [IBM/cp4waiops-gitops#87]
We can take 3.3 folder as reference, and change other folder structure for releases. Especially, 3.2 and 3.3, they need to be consistent, so that the same set of all-in-one chart can be applied to both.

**Comment by gyliu513** [comment]
@morningspace I think we do not need to update 3.2, as both 3.2 and 3.1 are not official release for us, but only 3.3 now, can we close this one?

**Comment by morningspace** [comment]
I'd suggest to update 3.2 at least given it's not a big change. The reason for that is, we have the use case such as x-small support for 3.2 customer, and the current all-in-one chart is actually a single chart that supports both 3.2 and 3.3 which have been tested already. BTW: We do not have per release all-in-one chart.

**Comment by liyanwei93** [comment]
Done in branch release-3.3
